# Talos recommended Config
ipam:
  mode: kubernetes
kubeProxyReplacement: true
securityContext:
  capabilities:
    ciliumAgent:
    - CHOWN
    - KILL
    - NET_ADMIN
    - NET_RAW
    - IPC_LOCK
    - SYS_ADMIN
    - SYS_RESOURCE
    - DAC_OVERRIDE
    - FOWNER
    - SETGID
    - SETUID
    cleanCiliumState:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
k8sServiceHost: localhost
k8sServicePort: 7445
# My Config

# scale down cilium-operator for single node
operator:
  replicas: 1

# Enable cilium Ingress and GatewayAPI
ingressController:
  enabled: true
  default: true
  enforceHttps: false
  loadbalancerMode: shared        # use a shared envory-instance for all ingresses
  hostNetwork:
    enabled: true
    sharedListenerPort: 80
  # service:
  #   type: NodePort
  #   insecureNodePort: 80
  #   secureNodePort: 443
nodePort:
  enabled: true
l7Proxy: true
envoy:
  enabled: true
  securityContext:
    capabilities:
      keepCapNetBindService: true
      envoy:
      # Add NET_BIND_SERVICE to the list (keep the others!)
      - NET_ADMIN
      - SYS_ADMIN
      - NET_BIND_SERVICE
gatewayAPI:
  enabled: true
  hostNetwork:
    enabled: true

hostPort:
  enabled: true
hubble:
  relay:
    enabled: true
  ui:
    enabled: true