apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp-admin
  namespace: headlamp

---
apiVersion: v1
kind: Secret
metadata:
  name: headlamp-admin-secret
  namespace: headlamp
  annotations:
    kubernetes.io/service-account.name: headlamp-admin
type: kubernetes.io/service-account-token

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: headlamp-admin
  namespace: headlamp

---
kind: Service
apiVersion: v1
metadata:
  name: headlamp
  namespace: headlamp
spec:
  ports:
    - port: 80
      targetPort: 4466
  selector:
    k8s-app: headlamp
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: headlamp
  namespace: headlamp
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: headlamp
  template:
    metadata:
      labels:
        k8s-app: headlamp
    spec:
      containers:
        - name: headlamp
          image: ghcr.io/headlamp-k8s/headlamp:v0.31.1
          args:
            - -in-cluster
            - -plugins-dir=/headlamp/plugins
            - -oidc-idp-issuer-url=https://dex.buc.sh
            - -oidc-client-id=login
            - -oidc-client-secret="notaSecretDexisLocal"
            - -oidc-scopes=profile,email,groups
          env:
            - name: HEADLAMP_CONFIG_METRICS_ENABLED
              value: "true"
            # - name: HEADLAMP_CONFIG_TRACING_ENABLED
            #   value: "true"
            # - name: HEADLAMP_CONFIG_OTLP_ENDPOINT
            #   value: "otel-collector:4317"
            - name: HEADLAMP_CONFIG_SERVICE_NAME
              value: "headlamp"
            - name: HEADLAMP_CONFIG_SERVICE_VERSION
              value: "latest"
          ports:
            - containerPort: 4466
              name: http
            - containerPort: 9090
              name: metrics
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 4466
            initialDelaySeconds: 30
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 4466
            initialDelaySeconds: 30
            timeoutSeconds: 30
# ---
# kind: Secret
# apiVersion: v1
# metadata:
#   name: headlamp-admin
#   namespace: headlamp
#   annotations:
#     kubernetes.io/service-account.name: "headlamp-admin"
# type: kubernetes.io/service-account-token

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headlamp-http
spec:
  rules:
  - host: homelab-console.10.0.0.23.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: headlamp
            port:
              number: 80
